# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
  - &bash_cache automattic/bash-cache#2.10.0
  env: &common_env
    IMAGE_ID: xcode-14.1

# This is the default pipeline – it will build and test the pod
steps:
  ########################
  # Validate Swift Package
  ########################
  - label: "🔬 Validate Swift Package"
    key: "test"
    command: "validate_swift_package"
    env: *common_env
    plugins: *common_plugins

  #################
  # Validate Podspec
  #################
  - label: "🔬 Validate Podspec"
    key: "validate"
    command: "validate_podspec"
    env: *common_env
    plugins: *common_plugins

  #################
  # Lint
  #################
  - label: "🧹 Lint"
    key: "lint"
    command: "lint_pod"
    env: *common_env
    plugins: *common_plugins

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Podspec"
    key: "publish"
    command: .buildkite/publish-pod.sh
    env: *common_env
    plugins: *common_plugins
    depends_on:
      - "test"
      - "validate"
      - "lint"
    if: build.tag != null
    agents:
      queue: "mac"
