source 'https://cdn.cocoapods.org/'

target 'WPXMLRPCTest-OSX' do
  platform :osx, '10.9'
  pod "wpxmlrpc", :path => "../"
  pod 'CTidy', '~> 0.3'
end

target 'WPXMLRPCTest-iOS' do
  platform :ios, '9.0'
  pod "wpxmlrpc", :path => "../" 
  pod 'CTidy', '~> 0.3'
end
